spring:
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    active: development

  security:
    user:
      name: user
      password: user

  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  pattern:
    #console: "%d %-20level %logger : %msg%n"

server:
  port: 8080
